version: '3.8'

services:
  traefik:
    image: traefik:v2.11
    container_name: traefik
    ports:
      - "8080:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./conf:/etc/traefik
    command:
      - --log.level=DEBUG