
http:
  routers:
    vue-router:
      rule: "PathPrefix(`/vue-micro-app`) || PathPrefix(`/vue-micro-app-assets`)"
      service: vue-app
    next-router:
      rule: "!PathPrefix(`/vue-micro-app`) && !PathPrefix(`/vue-micro-app-assets`)"
      service: next-app

  services:
    vue-app:
      loadBalancer:
        servers:
          - url: "http://host.docker.internal:3002/"
    next-app:
      loadBalancer:
        servers:
          - url: "http://host.docker.internal:3000/"